source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YelpAPI_Example', :exclusive => true do
  pod "YelpAPI", :path => "../"
end

target 'YelpAPI_Tests', :exclusive => true do
  pod "YelpAPI", :path => "../"

  
end
